### ISSUE TITLE
빠른질문

### ISSUE THREAD

**Issue by cloud9350** [FullGreen/build_script#1]
Mali-400 드라이버가 올라와서 업데이트 시켜볼려고 하는데 drivers/gpu/mali400/r3p2 에 있는 폴더를 밀고 Pull request 할려 합니다. 가능한가요?

뭐.. 커널 포팅은 죄다 실패해봐서 모르겠지만요

**Comment by cloud9350** [comment]
https://github.com/FullGreen/fullgreen_kernel_samsung_smdk4412/tree/cm-13.0/drivers/gpu/mali400

**Comment by FullGreen** [comment]
넵, Pull request 하셔도 되요ㅎ

**Comment by cloud9350** [comment]
@FullGreen Commit 할려다가 예상외로 CyanogenMod 저장소에서 업데이트 해 놨었네요 :(
https://github.com/CyanogenMod/android_kernel_samsung_smdk4412/tree/cm-13.0/drivers/gpu/mali400
