### ISSUE TITLE
sms_patch.sh 가 없음.

### ISSUE THREAD

**Issue by cloud9350** [FullGreen/build_script#3]
![default](https://cloud.githubusercontent.com/assets/5405019/16723059/afdbed54-4785-11e6-8fa9-6c23c6f8e201.PNG)
오늘 새로 clone 해서 실행했는데 sms_patch.sh 파일이 없다고 나옵니다.

**Comment by FullGreen** [comment]
롬 소스가 있는 폴더안에 c1skt.sh와 sms_patch.sh가 같이 있는지 확인해주세요 :)

**Comment by cloud9350** [comment]
![default](https://cloud.githubusercontent.com/assets/5405019/16724221/a50236fc-478c-11e6-866e-d93d2bcef343.PNG)
sms_patch.sh 만 없으며 sms_patch.java 은 명령어에 의해 옮겨진 상태입니다.

**Comment by FullGreen** [comment]
앗... sms_patch.java 인데 오타났어요...ㅋㅋㅋ

**Comment by cloud9350** [comment]
@FullGreen 대량으로 오타를 치셨군요 ㅋ

**Comment by cloud9350** [comment]
[https://github.com/FullGreen/build_script/commit/70906b338e1f69bdbec6a623bcdf3e10bfb69b75]
